import esbuild from "esbuild";
import process from "process";
import { copyFile, mkdir } from "node:fs/promises";
import { builtinModules } from 'node:module';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const sync = (process.argv[3] === "sync");
const pluginInstallDir = process.env.IMAGE_SHELF_PLUGIN_DIR ?? process.env.MEDIA_VAULT_PLUGIN_DIR;
const releaseArtifacts = ["main.js", "manifest.json", "styles.css"];

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
};

if (prod) {
	await esbuild.build(buildOptions);
	if (sync) {
		await syncReleaseArtifacts();
	}
} else {
	const context = await esbuild.context(buildOptions);
	await context.watch();
}

async function syncReleaseArtifacts() {
	if (!pluginInstallDir) {
		throw new Error("Set IMAGE_SHELF_PLUGIN_DIR to the target vault plugin directory before syncing.");
	}
	await mkdir(pluginInstallDir, { recursive: true });
	await Promise.all(releaseArtifacts.map((artifact) => copyFile(artifact, `${pluginInstallDir}/${artifact}`)));
	console.log(`Synced release artifacts to ${pluginInstallDir}`);
}
